version: "2"

run:
  timeout: 5m
  issues-exit-code: 1
  tests: false
  relative-path-mode: gomod
  modules-download-mode: readonly
  go: '1.23'
  concurrency: 3

linters:
  default: standard
  enable:
    - dupl
    - dupword
    - errorlint
    - funcorder
    - funlen
    - goconst
    - gocritic
    - gosec
    - iface
    - importas
  settings:
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
  exclusions:
    paths:
      - ".txt"
      - ".gitignore"

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
    - swaggo
  settings:
    gci:
      no-inline-comments: true
      no-prefix-comments: true
    golines:
      max-len: 200
      tab-len: 8
  exclusions:
    warn-unused: true
    generated: strict
    paths:
      - ".*\\.my\\.go$"
      - lib/bad.go

issues:
  max-issues-per-linter: 50
  max-same-issues: 0

output:
  formats:
    text:
      path: ./path/to/output.txt
      print-linter-name: true
      print-issued-lines: true
      colors: true
    json:
      path: ./path/to/output.txt